#!/bin/bash

docker-compose build  # rebuilds images. Ensures new changes in repo are included

docker-compose -f /home/mosegui/ContainerProjects/autojupyter/docker-compose.yml up --abort-on-container-exit
